### ISSUE TITLE
Getting a "sk is not defined" error

### ISSUE THREAD

**Issue by rnhurt** [ljacobsson/cw-logs-insights-gpt#1]
I'm getting a couple of errors when I install this extension.

## Environment:
- MacBook Pro M1
- macOS 13.4 beta
- Chrome Version 112.0.5615.49 (Official Build) (arm64)

## Errors:
![image](https://user-images.githubusercontent.com/24466/230903825-4d89686a-d06e-46fb-9fb0-29a199d7afec.png)
![image](https://user-images.githubusercontent.com/24466/230903883-68559af0-c709-425d-89e7-cd0859366a8a.png)

**Comment by rnhurt** [comment]
I do get the "Convert to query" button, but when I press it nothing happens.

![image](https://user-images.githubusercontent.com/24466/230904051-8c065613-9cf1-4af8-91aa-6c8983f5ec02.png)

**Comment by ljacobsson** [comment]
Hi @rnhurt 

It sounds a bit like you haven't added quotes around your API key. The OpenAI API keys start with `sk-` and without quotes it would create an arithemtic expression of two undefined vars.

![image](https://user-images.githubusercontent.com/7579097/231856527-7f047866-26d6-4fba-9151-73bc78bf4f5a.png)

**Comment by rnhurt** [comment]
You were absolutely correct.  My `apiKey.js` was malformed.  Once I corrected that it started working.

Thanx!
